Architecture development
Nikolai-SE/Roguelike pull request #2
Opened 2023-04-09 14:57 UTC by Nikolai-SE

Выполнено задание: Архитектура Roguelike
Состав команды: Гамора К. Овчинников Е. Стойко Н. Суркис А.

2023-06-20 19:04 UTC, yurii-litvinov requested changes
В архитектуре не отражено наличие карты (хотя есть Cell-ы, непонятно, где они лежат), генерация карты и загрузка.

2023-06-20 19:04 UTC, yurii-litvinov commented on README.md
> +консольная графика, традиционная для этого жанра игр.
```suggestion
* консольная графика, традиционная для этого жанра игр.
```

2023-06-20 19:04 UTC, yurii-litvinov commented on README.md
> +![](images/Диаграмма%20случаев%20использования.drawio.svg)
Стрелки между ролями и случаями использования не рисуются, просто соединительные линии должны быть.

2023-06-20 19:04 UTC, yurii-litvinov commented on README.md
> +    Игрок. Является единственным пользователем системы в силу синглплеерности проекта.
Справедливости ради, даже если бы проект был мультиплеерным, роль игрока всё равно была бы одна

2023-06-20 19:04 UTC, yurii-litvinov commented on README.md
> +    Старт новой игры. Позволяет начать новую игру. Точкой расширения является возможность завершения игровой сессии.
Целью игрока вряд ли может быть старт игры. Сама игра — да, может (игры в этом плане особенные: наверное, единственный вид продуктов, целью использования которых является само использование).

2023-06-20 19:04 UTC, yurii-litvinov commented on README.md
> +## Описание типичного пользователя
:(

2023-06-20 19:04 UTC, yurii-litvinov commented on README.md
> +![Диаграмма классов](images/Диаграмма%20классов.drawio.svg)
- Как-то оно неочевидно отображается на диаграмму компонентов. Стоило тут компоненты тоже явно нарисовать.
- HUD имеет ассоциацию (точнее, композицию) с Personage, но также и атрибут типа Personage. Допустимо, но не нужно — если есть ассоциация, атрибуты можно не рисовать (они наглядности не добавляют).
- `list<Equipment>` правильнее рисовать как `Equipment [*]`.
- Статические атрибуты рисуются подчёркнутыми.

2023-06-20 19:04 UTC, yurii-litvinov commented on README.md
> +Класс реализует интерфейс для взаимодействия с отображением игрового мира. Обеспечивается это с пощью взаимодействия с консолью.
```suggestion
Класс реализует интерфейс для взаимодействия с отображением игрового мира. Обеспечивается это с помощью взаимодействия с консолью.
```

2023-06-20 19:04 UTC, yurii-litvinov commented on README.md
> +> `consoleApi`, с пощью которой класс может взаимодействовать с консолью.
```suggestion
> `consoleApi`, с помощью которой класс может взаимодействовать с консолью.
```

2023-06-20 19:04 UTC, yurii-litvinov commented on README.md
> +Интерфейс содержит минимальный набор методов, которые долны реализовавывать класса для того, чтобы их можно было отображать в игровом мире.
```suggestion
Интерфейс содержит минимальный набор методов, которые должны реализовавывать классы для того, чтобы их можно было отображать в игровом мире.
```

2023-06-20 19:04 UTC, yurii-litvinov commented on README.md
> +Представляет реализацию абстрактного класс ячеек, является элементов игрового мира, способна оторбражаться на экране пользователя, а также взаимодействовать с персонажем.
```suggestion
Представляет реализацию абстрактного класс ячеек, является элементом игрового мира, способна оторбражаться на экране пользователя, а также взаимодействовать с персонажем.
```

2023-06-20 19:04 UTC, yurii-litvinov commented on README.md
> +> `List<Equipment> unused` - список неиспользуемого обмундированиеобмундирования.
```suggestion
> `List<Equipment> unused` - список неиспользуемого обмундирования.
```

2023-06-20 19:04 UTC, yurii-litvinov commented on README.md
> +![Диаграмма последовательностей](images/Диаграмма%20последовательностей.drawio.svg)
Тут бы линию активации для актора, и чтобы она совпадала с линией жизни. Иначе получается, что он генерирует события, будучи неактивным.

2023-06-20 19:04 UTC, yurii-litvinov commented on README.md
> +## Architectural drivers
:(

2023-06-22 13:24 UTC, Nikolai-SE commented
Исправили замечания, https://github.com/Nikolai-SE/Roguelike/pull/18

2023-06-22 20:11 UTC, Nikolai-SE commented
"В архитектуре не отражено наличие карты (хотя есть Cell-ы, непонятно, где они лежат), генерация карты и загрузка."
Отражено в 3 итерации при разработке этих функциональностей: 
https://github.com/Nikolai-SE/Roguelike/tree/impl-03 
 https://github.com/Nikolai-SE/Roguelike/pull/13

2024-12-26 08:46 UTC, closed without merging