Roguelike, часть 1
Nikolai-SE/Roguelike pull request #4
Opened 2023-04-23 19:53 UTC by asurkis

Выполнено задание: Roguelike, часть 1
Состав команды: 
- Гамора К. 
- Овчинников Е. 
- Стойко Н. 
- Суркис А.

2023-04-23 22:55 UTC, Nikolai-SE approved these changes

2023-06-20 19:04 UTC, yurii-litvinov requested changes
Как я понял, загрузка из файла не реализована

2023-06-20 19:04 UTC, yurii-litvinov commented on README.md
> +Представляет реализацию абстрактного класс ячеек, является элементов игрового мира. Объекты этого класса способны оторбражаться на экране пользователя, а также взаимодействовать с персонажем.
```suggestion
Представляет реализацию абстрактного класс ячеек, является элементов игрового мира. Объекты этого класса способны отображаться на экране пользователя, а также взаимодействовать с персонажем.
```

2023-06-20 19:04 UTC, yurii-litvinov commented on README.md
> +> `div(Vector, number): Vector`, находит частное от деления объекта класса `Vector` на число.
Это не очень важно для архитектуры, можно было не описывать.

2023-06-20 19:04 UTC, yurii-litvinov commented on README.md
> +> `enemyStrategy` - стратегия, которая определяет поведения врежеской единицы
```suggestion
> `enemyStrategy` - стратегия, которая определяет поведения вражеской единицы
```

2023-06-20 19:04 UTC, yurii-litvinov commented on README.md
> +Стратегия, поведение врежской единицы.
```suggestion
Стратегия, поведение вражской единицы.
```

2023-06-20 19:04 UTC, yurii-litvinov commented on README.md
> +![Диаграмма классов](images/Диаграмма%20классов.drawio.svg)
Общие замечания к диаграмме тут такие же, как в домашке по архитектуре, стоит поправить. Плюс — HUD cсылается на Character, а он вроде называется Player, и ещё у вас что-то странное с композициями (Camera владеет GamePage? World имеет двух хозяев, хотя по смыслу он один?)

2023-06-20 19:04 UTC, yurii-litvinov commented on README.md
> +> `tryWalk(Vector): boolean`, попытаться сместить игрока величину смещения, переданную в первом параметре, если игрока удалось сместить, то возвращает `true`, в противном случае возвращает `false`.
```suggestion
> `tryWalk(Vector): boolean`, попытаться сместить игрока на величину смещения, переданную в первом параметре, если игрока удалось сместить, то возвращает `true`, в противном случае возвращает `false`.
```

2023-06-20 19:04 UTC, yurii-litvinov commented on src/common_constants.ts
> +export interface Vector {
Вот тут бы комментарии, чем описывать векторы в диздоке. Сопровождающие код вряд ли полезут в диздок узнавать, что это за код такой, и вряд ли будут обновлять диздок, меняя тут что-то.

2023-06-20 19:04 UTC, yurii-litvinov commented on src/display.ts
> +export class Camera {
И самому классу бы комментарий

2023-06-20 19:04 UTC, yurii-litvinov commented on src/vector.ts
> +export interface Vector {
Что-то это было уже в common_constants.ts

2023-06-20 19:04 UTC, yurii-litvinov commented on README.md
> +При любых изменениях исходного кода игра пересоберётся и перезапустится автоматически.
Управление персонажем бы ещё описали

2023-06-20 19:04 UTC, yurii-litvinov commented on src/game_rules.ts
> +                if(equip == null)
```suggestion
                if (equip == null)
```

2023-06-20 19:08 UTC, asurkis commented
> Как я понял, загрузка из файла не реализована

Как мы поняли, загрузка — это третья часть, разве нет?

2023-06-20 19:53 UTC, asurkis commented on src/vector.ts
> +export interface Vector {
В дальнейших частях заметили эту ошибку рефакторинга и исправили

2023-06-20 19:54 UTC, asurkis commented on README.md
> +![Диаграмма классов](images/Диаграмма%20классов.drawio.svg)
Поскольку Character — неоднозначное имя, я переименовал его в Player здесь и далее. Изображения композиций здесь и в дальнейших PR исправил

2023-06-21 15:30 UTC, yurii-litvinov approved these changes
Вам ещё +1 за загрузку из "файла", так что зачтена

2024-12-26 08:46 UTC, closed without merging